reporter: xcode

included:
  - {PROJECT_NAME}
  - {PROJECT_NAME}Tests
  - {PROJECT_NAME}UITests

excluded:
  - {PROJECT_NAME}Tests/Sources/Mocks/Sourcery/AutoMockable.generated.swift
  - {PROJECT_NAME}/Sources/Supports/Helpers/Rswift/R.generated.swift
  - Pods
  - Derived
  - DerivedData

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - file_types_order
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - xct_specific_matcher
  - yoda_condition
disabled_rules:
  - todo

attributes:
  always_on_same_line:
    - '@objc'
cyclomatic_complexity:
  warning: 18
line_length: 250
file_length: 1050
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned
force_unwrapping: error
function_parameter_count:
  - 6
  - 8
function_body_length:
  - 90
  - 100
type_body_length:
  - 450
  - 500
type_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60
  max_length:
    warning: 40
    error: 60
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 45
    error: 60
nesting:
  type_level:
    warning: 3
    error: 6
custom_rules:
  empty_count_zero:
    name: "Empty Count Violation"
    regex: (\.count\s*(==|!=|<|<=|>|>=)\s*0)
    message: "Prefer checking `isEmpty` over comparing `count` to zero. "
    severity: warning
  delegate:
    name: "delegate"
    regex: "(  var delegate)"
    message: "Please use `weak` for `delegate`. "
    severity: error
  comments_space:
    name: "Space After Comment"
    regex: (^ *//\w+)
    message: "There should be a space after //"
    severity: warning
    match_kinds: comment
  multiple_empty_lines:
    name: "Multiple Empty Lines"
    regex: "((?: *\n){3,})"
    message: "There are too many line breaks"
    severity: warning
  switch_enum:
    name: "Switch Enum"
    regex: (case \w+\.+rawValue:)
    message: "Don't use enum.rawValue in switch-case. Please convert value to enum first. "
    severity: error
  compile_lookup:
    name: "Compile Lookup"
    regex: ((var|let) \w+ = \[)
    message: "You need to give types to the array and dictionary. "
    severity: error
  weak_self_binding:
    name: "Weak Self Binding"
    regex: (let (?!this)\w+ = self[, ])
    message: "Please use `let this = self` instead. "
    severity: error
  unowned:
    name: "Unowned"
    regex: "(unowned)"
    message: "Please use `weak` instead. "
    severity: error
  empty_string:
    name: "Empty String"
    regex: ((!\w+.isNotEmpty)
    message: "Please use `isEmpty` instead. "
    severity: error
  bracket:
    name: "Bracket"
    regex: (\}\n{2,}\}|\{\n{2,}\{)
    message: "No empty line between two open or close brackets. "
    severity: warning
  query_string:
    name: "Query String"
    regex: ( [=!><]+ \\\(.*\))
    message: "Donot use the string interpolation syntax for query string. "
    severity: warning
